repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [
          "--python-version=3.14",
          "--ignore-missing-imports",
          "--check-untyped-defs",
          "--warn-unused-ignores",
          "--warn-return-any",
          "--no-implicit-optional",
        ]
        additional_dependencies: []
